### ISSUE TITLE
Dodge: Building classes dynamically

### ISSUE THREAD

**Issue by danielwo** [brandon-rhodes/python-patterns#12]
Small typo I think: In the example

```
# Imagine 2 filtered loggers and 3 output loggers.

filters = {
    'pattern': PatternFilteredLog,
    'severity': SeverityFilteredLog,
}
outputs = {
    'file': FileLog,
    'socket': SocketLog,
    'syslog': SyslogLog,
}

# Select the two classes we want to combine.

with open('config') as f:
    filter_name, output_name = f.read().split()

filter_cls = filters[filter_name]
output_cls = outputs[output_name]

# Build a new derived class (!)

name = filter_name.replace('Log', '') + output_name
cls = type(name, (filter_cls, output_cls), {})

# Call it as usual to produce an instance.

logger = cls(...)
```

the following code doesn't seem right:
`name = filter_name.replace('Log', '') + output_name`

as `filter_name` would be either `'pattern'` or `'severity'`. Maybe would make sense if `filter_name` was either `'PatternFilteredLog'` or `'SeverityFilteredLog'`, and similarly for `output_name`, as you go on to mention the example `PatternFilteredFileLog`.

**Comment by danielwo** [comment]
or maybe doing `filter_cls.__name__`, `output_cls.__name__` would be better.

**Comment by brandon-rhodes** [comment]
Oh, look, it's naming the class `patternfile`. That's not what I intended, you're right! I'll switch it to this:
```
name = filter_name.title() + output_name.title() + 'Log'
```
so that the name comes out at `PatternFileLog`. Thanks for pointing that out!
