### ISSUE TITLE
Could use return value from pyplot builder

### ISSUE THREAD

**Issue by donkirkby** [brandon-rhodes/python-patterns#4]
I think your pyplot example in the builder pattern is probably easier to read as it is, but it is possible to strictly follow the gang of four's stipulation that:

>Builder returns the product as a final step...

The `plot()` method returns a list of `Line2D` objects, and you can get the figure from them. Here's a modified version of your example:

```
import numpy as np
x = np.arange(-6.2, 6.2, 0.1)

import matplotlib.pyplot as plt
lines = plt.plot(x, np.sin(x))
lines[0].figure.savefig('sine.png')
```

Feel free to use this however you like or ignore it. Thanks again for the articles.

**Comment by brandon-rhodes** [comment]
That's an interesting suggestion! I'll keep this open for a few days while I think about it; though, as you say, it's going to be tempting to keep it as-is for readability and to agree with the pyplot tutorials. I'll let you know what I decide!

**Comment by brandon-rhodes** [comment]
For now I'm going to leave it unchanged "for readability and to agree with the pyplot tutorials", as I reasoned above. I'll re-open this if I decide to revisit the issue in the future. Thanks for your interest!
