### ISSUE TITLE
Generate pdf

### ISSUE THREAD

**Issue by inosjarv** [brandon-rhodes/python-patterns#8]
Hi, is there any functionality to convert whole website as a pdf?

Thanks in advance :)

**Comment by brandon-rhodes** [comment]
It is a Sphinx project, so try checking out the Sphinx documentation — it should have a guide to building a PDF, if I recall.

**Comment by inosjarv** [comment]
_! Package inputenc Error: Unicode character − (U+2212)
(inputenc)                not set up for use with LaTeX._

getting this error while generating pdf while running
`make latexpdf`

**Comment by brandon-rhodes** [comment]
Alas, I had hoped it might succeed easily. I wonder why LaTeX would not be able to handle a minus sign?

**Comment by inosjarv** [comment]
Here is something I found regarding this error.
`[inpuenc Error](https://tex.stackexchange.com/questions/83440/inputenc-error-unicode-char-u8-not-set-up-for-use-with-latex)`

**Comment by brandon-rhodes** [comment]
Thanks for the link! I am not, alas, going to have time in the near future to take this on as a new project in addition to my current projects, but I’m happy to leave this issue open for you to post any further notes you take as you explore getting the Sphinx LaTeX mechanism working.

**Comment by inosjarv** [comment]
`------------
Run number 1 of rule 'pdflatex'
------------
------------
Running 'xelatex   -recorder  "PythonPatterns.tex"'
------------
sh: 1: xelatex: not found
Latexmk: fls file doesn't appear to have been made.
Latexmk: Errors, so I did not complete making targets
Collected error summary (may duplicate other messages):
  pdflatex: Command for 'pdflatex' gave return code 127
      Refer to 'PythonPatterns.log' for details
----------------------
This message may duplicate earlier message.
Latexmk: Failure in processing file 'PythonPatterns.tex':
   (Pdf)LaTeX didn't generate the expected log file 'PythonPatterns.log'
----------------------
Latexmk: Use the -f option to force complete processing,
`
getting this error while runnning
`make latexpdf`

**Comment by ethmcc** [comment]
> ## sh: 1: xelatex: not found

You need to install `xelatex`.

**Comment by inosjarv** [comment]
! You can't use `\numexpr' in restricted horizontal mode.
! Package fontspec Error: The font "FreeSerif" cannot be found.
I have already installed font, still it was not working.

**Comment by ethmcc** [comment]
I am unable to replicate your issue.

Sphinx defaults to using GNU `FreeSerif`, `FreeSans`, and `FreeMono` for broad compatibility, but fonts are still a system-dependent issue. Both what name the font is installed under and which directory it's located in will matter. 

You can look at the [Sphinx documentation for info on how to set the LaTeX fonts](https://www.sphinx-doc.org/en/master/latex.html) using entries in the `latex_elements` dict that's declared in `conf.py`.

**Comment by brandon-rhodes** [comment]
As printing this project as a PDF is not at this point a goal of the project — and as it looks like Sphinx's creaky mechanisms for doing so are causing problems for users who try to use them — I'm going to close this issue.

Thanks for everyone's contributions, though, who tried to make it work (or who got it working at least locally for them)!

And, everyone involved, please feel free to continue discussion here as long as you want. But having the issue closed with help keep my dashboard manageable. Thanks!
